all:
	g++ main.cpp syscall.c -o daemon -Wall libcontext.so -I../piga-systrans/src/libcontext_src

debug:
	g++ main.cpp syscall.c -o daemon -DDEBUG -Wall libcontext.so -I../piga-systrans/src/libcontext_src

